export const styles = {
  header: {
    position: "relative",
    height: "3.5rem",
    fontSize: "1rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0px 50px",
    gap: "70rem",
    boxShadow: " rgba(99, 99, 99, 0.2) 0px 2px 8px 0px",
    color: "gray",
  },
  headerButtonAndLogo: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sideBarButtonIcon: {
    display: "flex",
    alignItems: "center",
    height: "3.5rem",
    position: "absolute",
    left: "22px",
    top: "50%",
    transform: "translateY(-50%)",
    cursor: "pointer",
  },
  logoWraper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: "55px",
    width: "5rem",
    height: "3.5rem",
  },
  logo: {
    width: "4rem",
    height: "2rem",
  },
  userInfo: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  userAvatarWraper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "35px",
    height: "35px",
    borderRadius: "50px ",
  },
  userAvatar: {
    width: "25px",
    height: "25px",
  },
};
